package gcr.cli.android.sockets;

public enum ConnectionStatus {
    // RECEIVER STATUS
    RECEIVER_START,
    RECEIVER_WAITING_FOR_SENDER,
    RECEIVER_CONNECTED,
    RECEIVER_REFUSED,
    RECEIVER_DISCONNECTED,
    RECEIVER_TIMEOUT,
    // SENDER STATUS
    SENDER_CONNECTED,
    SENDER_REFUSED,
    SENDER_DISCONNECTED
}
